version: '3.4'
services:
  bitbucket:
    image: haxqer/bitbucket:7.21.16
    container_name: bitbucket-srv
    environment:
      - TZ=Asia/Shanghai
#      - JVM_MINIMUM_MEMORY=1g
#      - JVM_MAXIMUM_MEMORY=12g
#      - JVM_CODE_CACHE_ARGS='-XX:InitialCodeCacheSize=1g -XX:ReservedCodeCacheSize=8g'
    depends_on:
      - mysql
    ports:
      - "7990:7990"
      - "7999:7999"
    volumes:
      - home_data:/var/bitbucket
    restart: always
    networks:
      - network-bridge

  mysql:
    image: mysql:8
    container_name: mysql-bitbucket
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=bitbucket
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=bitbucket
      - MYSQL_PASSWORD=123123
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_bin']
#    ports:
#      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - network-bridge

networks:
  network-bridge:
    driver: bridge

volumes:
  home_data:
    external: false
  mysql_data:
    external: false
