version: '3.4'
services:
  bitbucket:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bitbucket-srv
    environment:
      - TZ=Asia/Shanghai
      - JDBC_DRIVER=org.postgresql.Driver
      - JDBC_URL=jdbc:postgresql://postgres:5432/bitbucket
      - JDBC_USER=bitbucket
      - JDBC_PASSWORD=bitbucket
    depends_on:
      - postgres
    ports:
      - "7990:7990"
      - "7999:7999"
    volumes:
      - home_data:/var/bitbucket
    restart: always
    networks:
      - network-bridge

  postgres:
    image: postgres:13
    container_name: postgres-bitbucket
    environment:
      - POSTGRES_DB=bitbucket
      - POSTGRES_USER=bitbucket
      - POSTGRES_PASSWORD=bitbucket
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - network-bridge

networks:
  network-bridge:
    driver: bridge

volumes:
  home_data:
    external: false
  postgres_data:
    external: false
