FROM openjdk:8-bullseye

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends git fontconfig openssh-client perl python3 python3-jinja2 tini \
    && apt-get clean autoclean && apt-get autoremove -y && rm -rf /var/lib/apt/lists/* \

